var Auth = require('../Auth');

Auth.prototype.authenticate = require('./authenticate');
// Auth.prototype.changeEmail = require('./changeEmail');
// Auth.prototype.changePassword = require('./changePassword');
// Auth.prototype.confirmEmail = require('./confirmEmail');
Auth.prototype.getUserByEmail = require('./getUserByEmail');
// Auth.prototype.getUserBySecret = require('./getUserBySecret');
Auth.prototype.login = require('./login');
Auth.prototype.logout = require('./logout');
Auth.prototype.passwordMatch = require('./passwordMatch');
Auth.prototype.register = require('./register');
Auth.prototype.registerProvider = require('./registerProvider');
// Auth.prototype.resetPassword = require('./resetPassword');
// Auth.prototype.resetPasswordSecret = require('./resetPasswordSecret');
// Auth.prototype.setPassword = require('./setPassword');
// Auth.prototype.userExists = require('./userExists');
// Auth.prototype.verifyCallback = require('./verifyCallback');
// Auth.prototype.createUser = require('./createUser');
